[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stealth_cash = "5Ta8DofvfQ8FoJvwjApYe7jbXqqwT4UpXrBXBX3eTVxz"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/home/ilia/Desktop/stealth-cash/wallets/w1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
