[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
stealth_cash = "GZFcqq4j4ptgHMVnFk8t4hDxCRS5Rrt1aNCBNj4hX3Lt"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/ilia/Desktop/stealth-cash/wallets/w1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"